# docker build -t ai.tencentmusic.com/tme-public/notebook:jupyter-ubuntu-gpu-base -f Dockerfile-ubuntu-gpu-base .

FROM gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu:1.0.0

USER root

ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

# 安装中文，和基础的apt工具包
RUN apt update && apt install -y --force-yes --no-install-recommends vim ca-certificates-java rsync jq  wget dnsutils iputils-ping net-tools curl locales ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy && \
    locale-gen zh_CN && locale-gen zh_CN.utf8

# 安装pip包
RUN pip install gsutil pysnooper psycopg2-binary pymysql kubernetes simplejson sqlalchemy redis pandas joblib numpy xgboost scikit-learn seldon-core tornado sklearn keras

RUN echo "alias ll='ls -alF'" >> /root/.bashrc && \
    echo "alias la='ls -A'" >> /root/.bashrc && \
    echo "alias vi='vim'" >> /root/.bashrc && \
    source /root/.bashrc

# 添加代码，源
# COPY src /src

# ENV PYTHONPATH=/src/pipelines/sdk/python/:/src/fairing/:/src/kfserving/python/kfserving/:/src/tf-operator/sdk/python/:$PYTHONPATH









