# docker build -t ai.tencentmusic.com/tme-public/notebook:jupyter-ubuntu-cpu-base -f Dockerfile-ubuntu-cpu-base .
FROM ubuntu:18.04
USER root
# 安装中文，和基础的apt工具包
RUN apt update && apt install -y --force-yes --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git dnsutils iputils-ping net-tools curl mysql-client locales ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy && \
    locale-gen zh_CN && locale-gen zh_CN.utf8

RUN curl -LO https://dl.k8s.io/release/v1.16.0/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/

ENV LANG zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8

RUN echo "alias ll='ls -alF'" >> /root/.bashrc && \
    echo "alias la='ls -A'" >> /root/.bashrc && \
    echo "alias vi='vim'" >> /root/.bashrc && \
    /bin/bash -c "source /root/.bashrc"

# 安装python pip环境
RUN apt install -y python3 python3-pip python3-dev && ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip && pip3 install --upgrade pip
# 安装python包
RUN pip3 install gsutil pysnooper psycopg2-binary jupyter-tensorboard kubernetes simplejson sqlalchemy redis pandas joblib numpy xgboost tensorflow==2.2 scikit-learn seldon-core tornado sklearn keras torch torchvision kazoo jinja2 requests numpy pandas flask pymysql Flask-APScheduler pysnooper pyyaml kubernetes jupyterlab voila notebook && \
    rm -rf /tmp/* /var/tmp/* /root/.cache

# 安装最新版的nodejs
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get install -y nodejs && npm config set unicode false

# 环境变量
ENV NODE_HOME /usr/local
ENV PATH $NODE_HOME/bin:$PATH
ENV NODE_PATH $NODE_HOME/lib/node_modules:$PATH
ENV SHELL /bin/bash

# jupyter lab --notebook-dir=/home --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'

# from tensorboard import version; print(version.VERSION)
# import tensorflow as tf; print(tf.__version__)


