{
 "title": "gpu",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "pod GPU 利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod!=''}",
     "legendFormat": "{{exported_pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "pod GPU 占用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod!=''}",
     "legendFormat": "{{exported_pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{instance}} GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU 内存利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_MEM_COPY_UTIL", "legendFormat": "{{instance}} GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "${{instance}} GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{instance}} GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_SM_CLOCK* 1000000", "legendFormat": "{{instance}} GPU {{gpu}}" }
   ]
  }
 ]
}