{
 "title": "istio service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(istio_requests_total, destination_service_namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_namespace=\"$namespace\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "qps(1min average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_workload,response_code) (irate(istio_requests_total{destination_service_namespace=\"$namespace\",destination_workload=~\"($service)\"}[1m]))",
     "legendFormat": "{{response_code}} , {{destination_workload}}"
    }
   ]
  },
  {
   "title": "Throughput（1min average）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_workload) (irate(istio_request_bytes_sum{destination_service_namespace=\"$namespace\",destination_workload=~\"($service)\"}[1m]))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", container=\"\",pod=~\".*$service.*\"}",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", container=\"\",pod=~\".*$service.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod GPU Memory Usage Util",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{pod=~'.*$service.*'}/(DCGM_FI_DEV_FB_USED{pod=~'.*$service.*'} + DCGM_FI_DEV_FB_FREE{pod=~'.*$service.*'})",
     "legendFormat": "{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "pod GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=~\".*$service.*\"}",
     "legendFormat": "{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "pod NPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_used_memory{pod_name=~'.*$service.*'}",
     "legendFormat": "{{pod_name}} {{model_name}} NPU {{id}}"
    }
   ]
  },
  {
   "title": "pod NPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_utilization{pod_name=~\".*$service.*\"}",
     "legendFormat": "{{pod_name}} {{model_name}} NPU {{id}}"
    }
   ]
  },
  {
   "title": "VGPU GPU Memory Allocated(GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vGPUPodsDeviceAllocated{podname=~\"$service.*\"}",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "VGPU Request Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vGPUMemoryPercentage{podname=~\"$service.*\"}",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "VGPU GPU Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Device_memory_desc_of_container{ctrname=~\"$service\"}",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "VGPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Device_utilization_desc_of_container{ctrname=~\"$service\"}",
     "legendFormat": "{{podname}}"
    }
   ]
  }
 ]
}