docker pull ccr.ccs.tencentyun.com/cube-studio/kubernetesui-dashboard:v2.6.1 && docker tag ccr.ccs.tencentyun.com/cube-studio/kubernetesui-dashboard:v2.6.1 kubernetesui/dashboard:v2.6.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/minio-minio:RELEASE.2023-04-20T17-56-55Z && docker tag ccr.ccs.tencentyun.com/cube-studio/minio-minio:RELEASE.2023-04-20T17-56-55Z minio/minio:RELEASE.2023-04-20T17-56-55Z &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-controller-manager:v1.7.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-controller-manager:v1.7.0 volcanosh/vc-controller-manager:v1.7.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/mysql:8.0.32 && docker tag ccr.ccs.tencentyun.com/cube-studio/mysql:8.0.32 mysql:8.0.32 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu:20.04 && docker tag ccr.ccs.tencentyun.com/cube-studio/ubuntu:20.04 ubuntu:20.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/busybox:1.36.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/busybox:1.36.0 busybox:1.36.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/nvidia-dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 && docker tag ccr.ccs.tencentyun.com/cube-studio/nvidia-dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/alpine:3.10 && docker tag ccr.ccs.tencentyun.com/cube-studio/alpine:3.10 alpine:3.10 &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-webhook-manager:v1.7.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-webhook-manager:v1.7.0 volcanosh/vc-webhook-manager:v1.7.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/argoproj-workflow-controller:v3.4.3 && docker tag ccr.ccs.tencentyun.com/cube-studio/argoproj-workflow-controller:v3.4.3 argoproj/workflow-controller:v3.4.3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 && docker tag ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/argoproj-argocli:v3.4.3 && docker tag ccr.ccs.tencentyun.com/cube-studio/argoproj-argocli:v3.4.3 argoproj/argocli:v3.4.3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/nvidia-k8s-device-plugin:v0.11.0-ubuntu20.04 && docker tag ccr.ccs.tencentyun.com/cube-studio/nvidia-k8s-device-plugin:v0.11.0-ubuntu20.04 nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/quay.io-prometheus-operator-prometheus-config-reloader:v0.46.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/quay.io-prometheus-operator-prometheus-config-reloader:v0.46.0 quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/grafana-grafana:9.1.5 && docker tag ccr.ccs.tencentyun.com/cube-studio/grafana-grafana:9.1.5 grafana/grafana:9.1.5 &
docker pull ccr.ccs.tencentyun.com/cube-studio/prom-prometheus:v2.27.1 && docker tag ccr.ccs.tencentyun.com/cube-studio/prom-prometheus:v2.27.1 prom/prometheus:v2.27.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/kubernetesui-metrics-scraper:v1.0.8 && docker tag ccr.ccs.tencentyun.com/cube-studio/kubernetesui-metrics-scraper:v1.0.8 kubernetesui/metrics-scraper:v1.0.8 &
docker pull ccr.ccs.tencentyun.com/cube-studio/argoproj-argoexec:v3.4.3 && docker tag ccr.ccs.tencentyun.com/cube-studio/argoproj-argoexec:v3.4.3 argoproj/argoexec:v3.4.3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/carlosedp-addon-resizer:v1.8.4 && docker tag ccr.ccs.tencentyun.com/cube-studio/carlosedp-addon-resizer:v1.8.4 carlosedp/addon-resizer:v1.8.4 &
docker pull ccr.ccs.tencentyun.com/cube-studio/quay.io-prometheus-operator-prometheus-operator:v0.46.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/quay.io-prometheus-operator-prometheus-operator:v0.46.0 quay.io/prometheus-operator/prometheus-operator:v0.46.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-scheduler:v1.7.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/volcanosh-vc-scheduler:v1.7.0 volcanosh/vc-scheduler:v1.7.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/bitnami-redis:6.2.12 && docker tag ccr.ccs.tencentyun.com/cube-studio/bitnami-redis:6.2.12 bitnami/redis:6.2.12 &
docker pull ccr.ccs.tencentyun.com/cube-studio/istio-pilot:1.15.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/istio-pilot:1.15.0 istio/pilot:1.15.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/kubeflow-training-operator:v1-8a066f9 && docker tag ccr.ccs.tencentyun.com/cube-studio/kubeflow-training-operator:v1-8a066f9 kubeflow/training-operator:v1-8a066f9 &
docker pull ccr.ccs.tencentyun.com/cube-studio/prom-node-exporter:v1.5.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/prom-node-exporter:v1.5.0 prom/node-exporter:v1.5.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/bitnami-kube-rbac-proxy:0.14.1 && docker tag ccr.ccs.tencentyun.com/cube-studio/bitnami-kube-rbac-proxy:0.14.1 bitnami/kube-rbac-proxy:0.14.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 && docker tag ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/istio-proxyv2:1.15.0 && docker tag ccr.ccs.tencentyun.com/cube-studio/istio-proxyv2:1.15.0 istio/proxyv2:1.15.0 &

wait
