docker pull ccr.ccs.tencentyun.com/cube-studio/phpmyadmin &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_download:20221001 &
docker pull ccr.ccs.tencentyun.com/cube-studio/deploy-service:20211001 &
docker pull ccr.ccs.tencentyun.com/cube-studio/llama-factory:20240410 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-deeplearning &
docker pull ccr.ccs.tencentyun.com/cube-studio/torchserve:0.5.3-cpu &
docker pull ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-cpu-base &
docker pull ccr.ccs.tencentyun.com/cube-studio/ml-server:20240601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/datax:20240501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/patrikx3:latest &
docker pull ccr.ccs.tencentyun.com/cube-studio/llm-server:20240601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/tritonserver:22.07-py3 &
docker pull ccr.ccs.tencentyun.com/cube-studio/video-audio:20210601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 &
docker pull ccr.ccs.tencentyun.com/cube-studio/data-process:20230501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-cpu-1.0.0 &
docker pull ccr.ccs.tencentyun.com/cube-studio/tf:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcano:20230601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/yolov7:2024.01 &
docker pull ccr.ccs.tencentyun.com/cube-studio/pytorch:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04-cuda11.8.0-cudnn8 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-gpu-base &
docker pull ccr.ccs.tencentyun.com/cube-studio/datax:20230601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_register:20230501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/python:strong &
docker pull ccr.ccs.tencentyun.com/cube-studio/nni:20230601 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray:gpu-20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9 &
docker pull ccr.ccs.tencentyun.com/cube-studio/offline-predict:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/neo4j:4.4 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-bigdata &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-machinelearning &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray-sklearn:20230801 &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04 &
docker pull ccr.ccs.tencentyun.com/cube-studio/dataset:20230501 &
docker pull ccr.ccs.tencentyun.com/cube-studio/tfserving:2.3.4 &

wait
