"""empty message

Revision ID: 1932452d5690
Revises: ee3ff94383cb
Create Date: 2023-03-24 11:50:45.135815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1932452d5690'
down_revision = 'ee3ff94383cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('doc', sa.String(length=200), nullable=True),
    sa.Column('session_num', sa.String(length=200), nullable=True),
    sa.Column('chat_type', sa.String(length=200), nullable=True),
    sa.Column('hello', sa.String(length=200), nullable=True),
    sa.Column('pre_question', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=200), nullable=True),
    sa.Column('service_config', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=2000), nullable=True),
    sa.Column('expand', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('aihub', sa.Column('images', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aihub', 'images')
    op.drop_table('chat')
    # ### end Alembic commands ###
