"""empty message

Revision ID: 50fcabb17ffe
Revises: bad28acb1778
Create Date: 2023-02-11 17:42:58.843398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fcabb17ffe'
down_revision = 'bad28acb1778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aihub', sa.Column('expand', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aihub', 'expand')
    # ### end Alembic commands ###
