"""empty message

Revision ID: 583d4c1d254f
Revises: 8feab47444dc
Create Date: 2025-07-25 13:15:40.936177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '583d4c1d254f'
down_revision = '8feab47444dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('docker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namespace', sa.String(length=200), server_default='jupyter', nullable=True, comment='命名空间'))


    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namespace', sa.String(length=200), server_default='service', nullable=True, comment='命名空间'))


    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), server_default='pipeline', nullable=True, comment='任务流类型'))


    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namespace', sa.String(length=200), server_default='service', nullable=True, comment='命名空间'))


    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namespace', sa.String(length=100), server_default='pipeline', nullable=True, comment='命名空间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('namespace')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('namespace')

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.drop_column('namespace')

    with op.batch_alter_table('docker', schema=None) as batch_op:
        batch_op.drop_column('namespace')

    # ### end Alembic commands ###
