"""empty message

Revision ID: ee3ff94383cb
Revises: f2e7206f53c4
Create Date: 2023-02-13 19:20:32.882017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee3ff94383cb'
down_revision = 'f2e7206f53c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlab_query',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submit_time', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.String(length=40), nullable=False),
    sa.Column('end_time', sa.String(length=40), nullable=False),
    sa.Column('engine_arg1', sa.String(length=200), nullable=False),
    sa.Column('engine_arg2', sa.String(length=200), nullable=False),
    sa.Column('qsql', sa.String(length=5000), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('deli', sa.String(length=11), nullable=False),
    sa.Column('stage', sa.String(length=11), nullable=False),
    sa.Column('status', sa.String(length=11), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('log_url', sa.String(length=400), nullable=False),
    sa.Column('ui_url', sa.String(length=400), nullable=False),
    sa.Column('result_url', sa.String(length=400), nullable=False),
    sa.Column('result_line_num', sa.String(length=400), nullable=False),
    sa.Column('err_msg', sa.String(length=5000), nullable=False),
    sa.Column('username', sa.String(length=400), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('idex_query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idex_query',
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('submit_time', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('start_time', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('end_time', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('group_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('qsql', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('engine', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('deli', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('stage', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('gaia_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('spark_log_url', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('spark_ui_url', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('result_url', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('result_line_num', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('err_msg', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('rtx', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('biz', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='idex_query_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='idex_query_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('sqlab_query')
    # ### end Alembic commands ###
