"""empty message

Revision ID: f2e7206f53c4
Revises: 50fcabb17ffe
Create Date: 2023-02-12 11:32:43.625772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e7206f53c4'
down_revision = '50fcabb17ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('env', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebook', 'env')
    # ### end Alembic commands ###
