
## 构建应用镜像 docker build -t ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.4-python3.9  -f Dockerfile-modelscope .
#FROM ccr.ccs.tencentyun.com/cube-studio/aihub:base-cuda11.4-python3.9
#
#RUN apt-get install libsndfile1
#
#RUN pip3 install torch torchvision torchaudio modelscope deepspeed tensorflow-gpu==1.15 -i https://pypi.tuna.tsinghua.edu.cn/simple
#RUN pip install "modelscope[nlp]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
#RUN pip install "modelscope[multi-modal]"
#RUN pip install "modelscope[cv]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
#RUN pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
#RUN pip install "modelscope[science]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
#RUN pip uninstall mmcv ; pip install -U openmim ; mim install mmcv-full


#docker build -t ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.3-python3.7  -f Dockerfile-modelscope .

FROM registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.3.2

# 安装
RUN pip3 install celery redis pyarrow requests_toolbelt cryptography tqdm fsspec aiohttp librosa flask werkzeug requests Pillow pysnooper opencv-python numpy && rm -rf ~/.cache

# cube-studio源码引入
RUN mkdir -p /data/log/nginx/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
ENV PYTHONPATH /src/:/github/:$PYTHONPATH
WORKDIR /app
