# docker build -t ccr.ccs.tencentyun.com/cube-studio/aihub:base-cuda11.4-python3.8  -f Dockerfile-cuda11.4-python3.8 .

FROM nvidia/cuda:11.4.0-runtime-ubuntu20.04

RUN apt update
ENV TZ Asia/Shanghai
ENV DEBIAN_FRONTEND noninteractive

# 安装运维工具
RUN apt install -y -f --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git dnsutils iputils-ping net-tools curl mysql-client locales zip unzip nginx lsof

# 安装中文
RUN apt install -y -f --no-install-recommends fontconfig locales ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy && locale-gen zh_CN && locale-gen zh_CN.utf8
ENV LANG zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8

# 便捷操作
RUN echo "alias ll='ls -alF'" >> /root/.bashrc && \
	echo "alias la='ls -A'" >> /root/.bashrc && \
	echo "alias vi='vim'" >> /root/.bashrc && \
	/bin/bash -c "source /root/.bashrc"

# 安装anaconda
RUN wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    mkdir /root/.conda && bash Miniconda3-latest-Linux-x86_64.sh -b && \
    rm -f Miniconda3-latest-Linux-x86_64.sh

# 激活python3.8
ENV PATH "/root/miniconda3/bin":$PATH
RUN conda create -y -n py38 python=3.8
ENV PATH /root/miniconda3/envs/py38/bin:$PATH
ENV CONDA_DEFAULT_ENV py38


# 安装
RUN apt install -y -f python3-opencv ffmpeg
RUN pip3 install flask werkzeug requests tornado Pillow pysnooper opencv-python numpy scipy matplotlib scikit-image ipython pyyaml visualdl filelock \
    && rm -rf ~/.cache

# 引入nginx
RUN mkdir -p /data/log/nginx/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
ENV PYTHONPATH /src/:/github/:$PYTHONPATH
WORKDIR /app
# ENTRYPOINT ["bash", "/entrypoint.sh"]

# docker run --name aihub --privileged -it -v $PWD:/app --entrypoint='' ccr.ccs.tencentyun.com/cube-studio/aihub:base-cuda11.4-python3.9 bash

