#docker build -t ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.3-python3.7  -f Dockerfile-modelscope .

FROM registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.3.2
ENV TZ Asia/Shanghai
ENV DEBIAN_FRONTEND noninteractive

# 安装运维工具
RUN apt install -y -f --no-install-recommends apt-transport-https gnupg2 jq dnsutils iputils-ping net-tools mysql-client locales zip unzip nginx lsof

# 安装
RUN pip3 install celery redis pyarrow requests_toolbelt cryptography tqdm fsspec aiohttp librosa flask werkzeug requests Pillow pysnooper opencv-python numpy && rm -rf ~/.cache

# cube-studio源码引入
RUN mkdir -p /data/log/nginx/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
ENV PYTHONPATH /src/:/github/:$PYTHONPATH
WORKDIR /app
