# docker build -t ccr.ccs.tencentyun.com/cube-studio/aihub:base-python3.6  -f Dockerfile-python3.6 .

FROM ubuntu:20.04

ARG PYTHONVERSION
ARG CONDAENV

RUN apt update
ENV TZ Asia/Shanghai
ENV DEBIAN_FRONTEND noninteractive

# 安装运维工具
RUN apt install -y -f --no-install-recommends vim apt-transport-https gnupg2 ca-certificates-java rsync jq  wget git dnsutils iputils-ping net-tools curl mysql-client locales zip unzip nginx lsof

# 安装中文
RUN apt install -y -f --no-install-recommends fontconfig locales ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy && locale-gen zh_CN && locale-gen zh_CN.utf8
ENV LANG zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8

# 便捷操作
RUN echo "alias ll='ls -alF'" >> /root/.bashrc && \
	echo "alias la='ls -A'" >> /root/.bashrc && \
	echo "alias vi='vim'" >> /root/.bashrc && \
	/bin/bash -c "source /root/.bashrc"

# 安装anaconda
RUN wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    mkdir /root/.conda && bash Miniconda3-latest-Linux-x86_64.sh -b && \
    rm -f Miniconda3-latest-Linux-x86_64.sh

# 激活python3
ENV PATH "/root/miniconda3/bin":$PATH
RUN conda create -y -n ${CONDAENV} python=${PYTHONVERSION}
ENV PATH /root/miniconda3/envs/${CONDAENV}/bin:$PATH
ENV CONDA_DEFAULT_ENV ${CONDAENV}

# 安装
RUN apt install -y -f python3-opencv ffmpeg
RUN pip3 install celery redis pyarrow requests_toolbelt cryptography tqdm fsspec aiohttp librosa flask werkzeug requests Pillow pysnooper opencv-python numpy && rm -rf ~/.cache

# cube-studio源码引入
RUN mkdir -p /data/log/nginx/
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
ENV PYTHONPATH /src/:/github/:$PYTHONPATH
WORKDIR /app
#ENTRYPOINT ["bash", "/entrypoint.sh"]

# docker run --name aihub --privileged -it -v $PWD:/app --entrypoint='' ccr.ccs.tencentyun.com/cube-studio/aihub:base-python3.6  bash

