
# 构建应用镜像 docker build -t ccr.ccs.tencentyun.com/cube-studio/modelscope:base-cuda11.4-python3.9  -f Dockerfile-modelscope .
FROM ccr.ccs.tencentyun.com/cube-studio/aihub:base-cuda11.4-python3.9

RUN apt-get install libsndfile1

RUN pip3 install torch torchvision torchaudio modelscope deepspeed tensorflow-gpu==1.15 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install "modelscope[nlp]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
RUN pip install "modelscope[multi-modal]"
RUN pip install "modelscope[cv]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
RUN pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
RUN pip install "modelscope[science]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
RUN pip uninstall mmcv ; pip install -U openmim ; mim install mmcv-full
