docker pull rancher/squareup-ghostunnel:v1.5.2 &
docker pull rancher/jimmidyson-configmap-reload:v0.2.2 &
docker pull rancher/k8s-dns-sidecar:1.15.2 &
docker pull rancher/longhornio-csi-resizer:v0.3.0 &
docker pull rancher/istio-kubectl:1.5.9 &
docker pull rancher/k8s-dns-kube-dns:1.15.10 &
docker pull rancher/coreos-flannel:v0.12.0 &
docker pull rancher/calico-ctl:v3.13.4 &
docker pull rancher/istio-kubectl:1.4.6 &
docker pull rancher/rancher-webhook:v0.1.0-beta7 &
docker pull rancher/log-aggregator:v0.1.7 &
docker pull busybox &
docker pull rancher/gitjob:v0.1.8 &
docker pull rancher/prom-node-exporter:v1.0.1 &
docker pull rancher/k8s-dns-node-cache:1.15.13 &
docker pull rancher/jetstack-cert-manager-controller:v0.8.1 &
docker pull rancher/tekton-utils:v0.1.0 &
docker pull rancher/klipper-helm:v0.3.0 &
docker pull rancher/hyperkube:v1.18.10-rancher1 &
docker pull rancher/configmap-reload:v0.3.0-rancher2 &
docker pull rancher/library-traefik:1.7.19 &
docker pull rancher/k8s-dns-dnsmasq-nanny:1.15.10 &
docker pull rancher/calico-ctl:v3.16.1 &
docker pull rancher/kube-api-auth:v0.1.4 &
docker pull rancher/jaegertracing-all-in-one:1.14 &
docker pull rancher/library-busybox:1.31.1 &
docker pull rancher/grafana-grafana:6.7.4 &
docker pull rancher/shell:v0.1.5 &
docker pull rancher/istio-pilot:1.7.3 &
docker pull rancher/istio-1.5-migration:0.1.1 &
docker pull rancher/k8s-dns-node-cache:1.15.7 &
docker pull registry:2 &
docker pull rancher/pause:3.2 &
docker pull rancher/opa-gatekeeper:v3.1.0-beta.7 &
docker pull rancher/calico-pod2daemon-flexvol:v3.16.1 &
docker pull rancher/flannel-cni:v0.3.0-rancher6 &
docker pull rancher/thanosio-thanos:v0.15.0 &
docker pull rancher/fluent-fluent-bit:1.5.4-debug &
docker pull rancher/kubectl:v1.18.0 &
docker pull rancher/istio-pilot:1.5.9 &
docker pull rancher/nginx-ingress-controller:nginx-0.35.0-rancher2 &
docker pull rancher/kubernetes-external-dns:v0.7.3 &
docker pull rancher/k8s-dns-kube-dns:1.15.0 &
docker pull rancher/pstauffer-curl:v1.0.3 &
docker pull rancher/fleet:v0.3.1 &
docker pull rancher/calico-pod2daemon-flexvol:v3.13.4 &
docker pull rancher/longhornio-csi-provisioner:v1.4.0 &
docker pull rancher/istio-coredns-plugin:0.2-istio-1.1 &
docker pull rancher/coreos-etcd:v3.3.15-rancher1 &
docker pull rancher/longhornio-longhorn-ui:v1.0.2 &
docker pull rancher/kiwigrid-k8s-sidecar:0.1.151 &
docker pull rancher/prom-prometheus:v2.12.0 &
docker pull rancher/pipeline-jenkins-server:v0.1.4 &
docker pull rancher/istio-citadel:1.5.9 &
docker pull rancher/local-path-provisioner:v0.0.14 &
docker pull rancher/security-scan:v0.1.14 &
docker pull rancher/k8s-dns-sidecar:1.15.10 &
docker pull rancher/plugins-docker:18.09 &
docker pull rancher/prom-prometheus:v2.18.2 &
docker pull rancher/rancher-agent:v2.5.2 &
docker pull rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1 &
docker pull rancher/kubectl:v1.18.6 &
docker pull rancher/coreos-etcd:v3.4.3-rancher1 &
docker pull rancher/longhornio-csi-attacher:v2.0.0 &
docker pull rancher/openzipkin-zipkin:2.14.2 &
docker pull rancher/calico-kube-controllers:v3.13.4 &
docker pull rancher/rancher-operator:v0.1.1 &
docker pull rancher/banzaicloud-logging-operator:3.6.0 &
docker pull rancher/fluentd:v0.1.19 &
docker pull rancher/fluent-fluent-bit:1.5.4 &
docker pull rancher/longhornio-csi-node-driver-registrar:v1.2.0 &
docker pull rancher/k3s-upgrade:v1.17.13-k3s2 &
docker pull rancher/library-nginx:1.19.2-alpine &
docker pull rancher/cis-operator:v1.0.1 &
docker pull rancher/coreos-prometheus-config-reloader:v0.38.1 &
docker pull rancher/k3s-upgrade:v1.18.10-k3s2 &
docker pull rancher/rancher-agent:v2.4.8 &
docker pull rancher/calico-node:v3.13.4 &
docker pull rancher/hyperkube:v1.16.15-rancher1 &
docker pull rancher/kiali-kiali:v1.17 &
docker pull rancher/rke-tools:v0.1.66 &
docker pull rancher/eks-operator:v1.0.4 &
docker pull rancher/longhornio-longhorn-instance-manager:v1_20200514 &
docker pull rancher/openpolicyagent-gatekeeper:v3.1.1 &
docker pull rancher/backup-restore-operator:v1.0.2 &
docker pull rancher/jenkins-jnlp-slave:3.35-4 &
docker pull rancher/klipper-helm:v0.2.7 &
docker pull rancher/webhook-receiver:v0.2.4 &
docker pull rancher/metrics-server:v0.3.6 &
docker pull rancher/local-path-provisioner:v0.0.11 &
docker pull rancher/istio-kubectl:1.5.10 &
docker pull rancher/calico-kube-controllers:v3.16.1 &
docker pull rancher/klipper-lb:v0.1.2 &
docker pull rancher/hyperkube:v1.19.3-rancher1 &
docker pull rancher/prom-alertmanager:v0.21.0 &
docker pull rancher/k8s-dns-dnsmasq-nanny:1.15.2 &
docker pull rancher/sonobuoy-sonobuoy:v0.16.3 &
docker pull rancher/calico-cni:v3.16.1 &
docker pull rancher/coreos-prometheus-operator:v0.38.1 &
docker pull rancher/prometheus-auth:v0.2.1 &
docker pull rancher/pushprox-client:v0.1.0-rancher1-client &
docker pull rancher/rancher:v2.5.2 &
docker pull rancher/cluster-proportional-autoscaler:1.7.1 &
docker pull rancher/coredns-coredns:1.6.2 &
docker pull rancher/kiali-kiali:v1.24.0 &
docker pull rancher/istio-installer:1.7.3-rancher2 &
docker pull rancher/longhornio-longhorn-engine:v1.0.2 &
docker pull rancher/pushprox-proxy:v0.1.0-rancher1-proxy &
docker pull rancher/fleet-agent:v0.3.1 &
docker pull rancher/istio-node-agent-k8s:1.5.9 &
docker pull rancher/system-upgrade-controller:v0.6.2 &
docker pull rancher/coreos-etcd:v3.4.13-rancher1 &
docker pull rancher/klipper-helm:v0.2.3 &
docker pull rancher/k3s-upgrade:v1.19.3-k3s2 &
docker pull rancher/metrics-server:v0.3.4 &
docker pull rancher/longhornio-longhorn-manager:v1.0.2 &
docker pull rancher/k8s-dns-kube-dns:1.15.2 &
docker pull rancher/hyperkube:v1.17.13-rancher1 &
docker pull rancher/istio-proxyv2:1.5.9 &
docker pull rancher/cluster-proportional-autoscaler:1.8.1 &
docker pull rancher/jettech-kube-webhook-certgen:v1.2.1 &
docker pull rancher/fluent-bit-out-syslog:0.1.0 &
docker pull rancher/pause:3.1 &
docker pull rancher/coreos-flannel:v0.13.0-rancher1 &
docker pull rancher/directxman12-k8s-prometheus-adapter-amd64:v0.6.0 &
docker pull rancher/istio-galley:1.5.9 &
docker pull rancher/jimmidyson-configmap-reload:v0.3.0 &
docker pull rancher/banzaicloud-fluentd:v1.11.2-alpine-2 &
docker pull rancher/pipeline-tools:v0.1.15 &
docker pull rancher/curlimages-curl:7.70.0 &
docker pull rancher/coredns-coredns:1.6.5 &
docker pull rancher/istio-sidecar_injector:1.5.9 &
docker pull rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z &
docker pull rancher/coredns-coredns:1.7.0 &
docker pull rancher/istio-mixer:1.5.9 &
docker pull rancher/coredns-coredns:1.6.9 &
docker pull rancher/istio-proxyv2:1.7.3 &
docker pull rancher/calico-cni:v3.13.4 &
docker pull rancher/k8s-dns-dnsmasq-nanny:1.15.0 &
docker pull rancher/calico-node:v3.16.1 &
docker pull rancher/k8s-dns-sidecar:1.15.0 &
docker pull rancher/grafana-grafana:7.1.5 &
docker pull rancher/security-scan:v0.2.1 &
docker pull rancher/istio-mixer:1.7.3 &
docker pull rancher/istio-install-cni:1.7.3 &
docker pull rancher/coreos-kube-state-metrics:v1.9.7 &

wait
