# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='com.tencent.tme.kubeflow',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ntest.proto\x12\x18\x63om.tencent.tme.kubeflow\"\x95\x02\n\x06Sample\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07joinKey\x18\x02 \x01(\t\x12\r\n\x05valid\x18\x03 \x01(\x08\x12\x36\n\x03\x63sv\x18\x04 \x03(\x0b\x32).com.tencent.tme.kubeflow.Sample.CsvEntry\x12\x42\n\textParams\x18\x05 \x03(\x0b\x32/.com.tencent.tme.kubeflow.Sample.ExtParamsEntry\x1a*\n\x08\x43svEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x30\n\x0e\x45xtParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)




_SAMPLE_CSVENTRY = _descriptor.Descriptor(
  name='CsvEntry',
  full_name='com.tencent.tme.kubeflow.Sample.CsvEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.tme.kubeflow.Sample.CsvEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.tme.kubeflow.Sample.CsvEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=268,
)

_SAMPLE_EXTPARAMSENTRY = _descriptor.Descriptor(
  name='ExtParamsEntry',
  full_name='com.tencent.tme.kubeflow.Sample.ExtParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.tme.kubeflow.Sample.ExtParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.tme.kubeflow.Sample.ExtParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=318,
)

_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='com.tencent.tme.kubeflow.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.tencent.tme.kubeflow.Sample.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joinKey', full_name='com.tencent.tme.kubeflow.Sample.joinKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='com.tencent.tme.kubeflow.Sample.valid', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='csv', full_name='com.tencent.tme.kubeflow.Sample.csv', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extParams', full_name='com.tencent.tme.kubeflow.Sample.extParams', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SAMPLE_CSVENTRY, _SAMPLE_EXTPARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=318,
)

_SAMPLE_CSVENTRY.containing_type = _SAMPLE
_SAMPLE_EXTPARAMSENTRY.containing_type = _SAMPLE
_SAMPLE.fields_by_name['csv'].message_type = _SAMPLE_CSVENTRY
_SAMPLE.fields_by_name['extParams'].message_type = _SAMPLE_EXTPARAMSENTRY
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {

  'CsvEntry' : _reflection.GeneratedProtocolMessageType('CsvEntry', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLE_CSVENTRY,
    '__module__' : 'test_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.tme.kubeflow.Sample.CsvEntry)
    })
  ,

  'ExtParamsEntry' : _reflection.GeneratedProtocolMessageType('ExtParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLE_EXTPARAMSENTRY,
    '__module__' : 'test_pb2'
    # @@protoc_insertion_point(class_scope:com.tencent.tme.kubeflow.Sample.ExtParamsEntry)
    })
  ,
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.tme.kubeflow.Sample)
  })
_sym_db.RegisterMessage(Sample)
_sym_db.RegisterMessage(Sample.CsvEntry)
_sym_db.RegisterMessage(Sample.ExtParamsEntry)


_SAMPLE_CSVENTRY._options = None
_SAMPLE_EXTPARAMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
